### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Fr33Radical** [elastic/ecs-logging-java#106]
Hi,
  Can someone explain me the best way to handle error?

  If the remote host get down, if the port got close or even if the firewall block the logs for some reason, I don't want to loose the logs.

  I tried a few solutions in log4j2 but none looks to work correctly.

  Is it possible to logs in a file if the socket appender fail?

  Note: Failover appender and "errorRef" of AsyncAppenders does not seems to work.

  I think ErrorHandling is an important aspect that has not been presented yet in this project.

  Thank you for any good information.

**Comment by felixbarny** [comment]
> If the remote host get down, if the port got close or even if the firewall block the logs for some reason, I don't want to loose the logs.

That's the risk you are opting into when logging directly over the network or when using async appenders.

If logging is business-critical (such as audit logs) and you rather stall the application than lose logs, I recommend synchronously logging to a file (or to stdout when running on containers). Then, shipping the files with Filebeat which can guarantee [at-least-once delivery](https://www.elastic.co/guide/en/beats/filebeat/current/how-filebeat-works.html#at-least-once-delivery).

I'm happy to give advice but it's not something that's in scope for this project, which just provides formatters. These are just the general tradeoffs of the different appenders which are maintained in the log4j2 repo.

**Comment by Fr33Radical** [comment]
Thank you for your answer. I am happy to share my solution.

This provide almost the entire solution.
[https://stackoverflow.com/questions/29843808/log4j2-2-0-1-async-appender-errorref-usage](url)

The only thing that miss to it and why it did not work is because you need to add the property ignoreExceptions="false" on the socket appender.

As specified here
[https://logging.apache.org/log4j/2.x/manual/appenders.html](url)
> "You must set this to false when wrapping this Appender in a FailoverAppender."

This solution works for all scenarios. Missing logs will be persist in a file temporary.
