### ISSUE TITLE
Add params for others service fields

### ISSUE THREAD

**Issue by vlaborie** [elastic/ecs-logging-java#113]
Ecs-logging-java permit to define the **service.name** but no others [service fields](https://www.elastic.co/guide/en/ecs/current/ecs-service.html).

Can you add params for **service.type** and **service.version** ?

**Comment by felixbarny** [comment]
You can add arbitrary additional fields. Example for log4j2:

```
  <KeyValuePair key="service.version " value="1.2.3"/>
```

**Comment by vlaborie** [comment]
It is also possible with jul and log4j ?

**Comment by felixbarny** [comment]
Currently, that's not possible. Would you be interested in contributing support for it?

**Comment by vlaborie** [comment]
I would, but i am not a Java developer.

Have you any plan to implement this in the near future ?

**Comment by felixbarny** [comment]
I see what I can do but I can't make promises.

As a workaround, could you just set all the information into `service.name`?

**Comment by vlaborie** [comment]
Thank's for adding additional fields to log4j and JUL.

I tested it and it work well for log4j but doesn't work for JUL.

I tried to add `co.elastic.logging.jul.EcsFormatter.additionalFields=key1=value1,key2=value2` in my Tomcat `logging.properties` like specified in documentation but nothing happened.

**Comment by felixbarny** [comment]
> Thank's for adding additional fields to log4j and JUL.
> 
> I tested it and it work well for log4j but doesn't work for JUL.
> 
> I tried to add co.elastic.logging.jul.EcsFormatter.additionalFields=key1=value1,key2=value2 in my Tomcat logging.properties like specified in documentation but nothing happened

Thanks for reporting. Not sure why you deleted that comment.
This should be fixed by #118
