### ISSUE TITLE
JUL EcsFormatter boolean parameter values are ignored

### ISSUE THREAD

**Issue by odonati-fr** [elastic/ecs-logging-java#133]
The boolean parameters values (in co.elastic.logging.jul.EcsFormatter's constructor) are loaded using java method [Boolean.getBoolean(property)](https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#getBoolean(java.lang.String)) instead of [Boolean.parseBoolean(string)](https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html#parseBoolean(java.lang.String)).

So if logging.properties contains:
`co.elastic.logging.jul.EcsFormatter.stackTraceAsArray=true`
the formatter property stackTraceAsArray will be true only if a system property named "true" with value "true" exists.

It's a workaround but I don't think it was intended that way.

**Comment by eyalkoren** [comment]
Sorry for the very long wait, we've been very busy 😄 

> It's a workaround but I don't think it was intended that way.

Definitely not intended this way. 

A test for stack-as-array would uncover that.
Once #177 is merged, I may include a general test within the fix for this issue.

Thanks for reporting!
