### ISSUE TITLE
Hooks for adding custom fields

### ISSUE THREAD

**Issue by echatman** [elastic/ecs-logging-java#147]
I would like to use co.elastic.logging.logback.EcsEncoder but I need to be able to add some custom fields. Some examples are: Exception root cause class, exception root cause message, and raw/unformatted log message.

I tried subclassing EcsEncoder, but since everything inside encode() is just static calls to EcsJsonSerializer, and all of the fields in EcsEncoder are private, I can't find any way to accomplish this.

**Comment by echatman** [comment]
Just finished testing out the idea in my previous comment and it doesn't work - the event gets it's own lazily-loaded copy of the MDC which can be populated before this point (for example: when using an AsyncAppender), so this is too late to add things to the MDC.

**Comment by felixbarny** [comment]
We could add a protected method in `EcsEncoder` that gets called in `encode`, before the JSON object is closed. By default, the method does nothing but can be used by subclasses to add custom stuff to the JSON. Would that work for you?

**Comment by robsonhermes** [comment]
@echatman thanks for adding this, it's perfect for my use case.

However, I extended the `EcsEncoder` in my spring + kotlin + logback project. When I replace the `EcsEncoder` with my own in logback config, the log is not produced in JSON anymore, but in the typical plain text format. 


Any ideas why?

```
class CustomEcsEncoder : EcsEncoder() {
    override fun addCustomFields(event: ILoggingEvent?, builder: StringBuilder?) {
        requireNotNull(event) { "A logging event is required but is null" }
        val logEventAdditionalFields = convertKeyValuePairsToAdditionalFields(event.keyValuePairs)
        serializeAdditionalFields(builder, logEventAdditionalFields)
    }

    private fun convertKeyValuePairsToAdditionalFields(keyValuePairs: List<KeyValuePair>): List<AdditionalField> =
        keyValuePairs.map { AdditionalField(it.key, it.value.toString()) }
}
```

**Comment by robsonhermes** [comment]
Nevermind, it works now. Actually the `event.keyValuePairs` can be null, so, in kotlin, I need to treat it as `List<KeyValuePair>?`
