### ISSUE TITLE
logback-encoder: Inconsistent usage of space character after comma

### ISSUE THREAD

**Issue by ChristianCiach** [elastic/ecs-logging-java#169]
This may seem like nitpicking, but I am sensitive to stuff like this and I think it really makes the JSON harder to read for humans:

I am evaluating `co.elastic.logging:logback-ecs-encoder:1.3.2` as a replacement for the logstash-encoder. It seems to work well, but... The encoder uses inconsistent whitespace after the comma character after each key-value-pair.

Example:

```json
{"@timestamp":"2022-03-21T18:31:40.855Z", "log.level": "INFO", "message":"Start creating calculation modules from configuration ...", "ecs.version": "1.2.0","process.thread.name":"main","log.logger":"my.company.modules.factory.ModuleFactory"}
```

As you can see, there is a space-character after the values for the `@timestamp`, the `log.level` the `message` value, but *not* after the values for `ecs.version` and `process.thread.name`. 

Again, this seems like a really small thing, but it also makes a bad first impression, especially since this format is advertised as a "Decently human-readable JSON structure" (https://www.elastic.co/guide/en/ecs-logging/overview/current/intro.html#_why_ecs_logging)

**Comment by felixbarny** [comment]
@ChristianCiach and @eyalkoren Would you expect that there's a space after every comma or never a space after a comma? Or are you indifferent as long as it's consistent?

I also noticed that some key:value pairs have a space after the colon while some don't

I'd say the most readable variants are either

No space after colon and a space after the comma
```json
{"key1":"value1", "key2":"value2"}
```
or a space after colon and a space after the comma
```json
{"key1": "value1", "key2": "value2"}
```

But personally, I don't have a strong opinion and don't mind the inconsistency too much.

**Comment by eyalkoren** [comment]
I printed it both as is and as pretty string and I wouldn't be able to tell the difference until pointed out for me.
Currently it's without any space in both cases. It's easier because I don't have to care about last or not.
Since its such low importance, I'd be happy to invest as little as possible in that.

**Comment by felixbarny** [comment]
Sounds good to me, too. At least it's consistent now.

Btw, the reason there's a space after log.level is to ensure the message always starts at the same location, no matter how many characters the value of log.level has:

```
"log.level": "INFO","message":"foo"
"log.level":"DEBUG","message":"foo"
```

**Comment by ChristianCiach** [comment]
Personally I would've preferred to always have a space after a comma, but consistency is way more important to me than my personal preferences. Thanks for "fixing" this!
