### ISSUE TITLE
Create a setter for "topLevelLabels"

### ISSUE THREAD

**Issue by Bjoern2** [elastic/ecs-logging-java#41]
Hi.
I want to set custom topLevelLabels in co.elastic.logging.logback.EcsEncoder. (E.g. "user.name".)
But there is no setter for this variable.
Could you please add a new setter for this variable? Thanks.
Greetings Björn

**Comment by felixbarny** [comment]
Would you be interested in creating a PR in `https://github.com/elastic/ecs-logging-java/blob/master/logback-ecs-encoder/src/main/java/co/elastic/logging/logback/EcsEncoder.java`? I think a `addTopLevelLabel` method might even be better than a setter.
