### ISSUE TITLE
log4j2-ecs-layout ignores log4j2.enable.threadlocals flag

### ISSUE THREAD

**Issue by vy** [elastic/ecs-logging-java#55]
`EcsJsonSerializer#messageStringBuilder` thread-local is allocated and used in `log4j2-ecs-layout` without taking `org.apache.logging.log4j.core.util.Constants.ENABLE_THREADLOCALS` into account.

**Comment by felixbarny** [comment]
This thread-local does not lead to classloader leaks as it does not contain application classes but only `StringBuilder` which is loaded from the bootstrap class loader.

Is there any other reason why `Constants.ENABLE_THREADLOCALS` should be taken into account?

**Comment by vy** [comment]
AFAIU, `Constants.ENABLE_THREADLOCALS` is an on/off button; not causing CL leaks in TLAs doesn't mean you can just ignore the flag. In its current form, user is given access to opt out from entire set of TLAs.

For details you can check [the relevant log4j-dev thread](https://lists.apache.org/thread.html/822e12dd384dd08d8e4899b474b855714ec97244e0365c461c0bd6d3%40%3Cdev.logging.apache.org%3E) where I have raised this issue.

As a follow-up of the discussion, I have also created [LOG4J2-2753](https://issues.apache.org/jira/browse/LOG4J2-2753), which proposes a similar fix to `AbstractStringLayout`.

**Comment by felixbarny** [comment]
This flag is mainly useful to avoid class loader leaks in web applications, not to avoid static memory overhead for threads. Because of that the flag is off by default in web apps which is not a good default in this case.
