### ISSUE TITLE
Allow the newline to be optional when stack trace is structured as an array

### ISSUE THREAD

**Issue by jcampaner** [elastic/ecs-logging-java#71]
Some log file observers have difficulty with newline characters. When a newline is encountered, it is presumed to be a separate log line. I'm having this problem when I have stackTraceAsArray="true" configured.

Each element of the array has a newline after it.
eg:
"error.stack_trace":[
	"stackelement1",
	"\tat stackelement2", 
	"\tat stackelement3", 
etc....] 

Would it be possible to optionally have the lines in an array, but not with newlines after each array element?

Eg:
"error.stack_trace":["stackelement1","\tat stackelement2", "\tat stackelement3", etc....]

**Comment by felixbarny** [comment]
Why don't you set `stackTraceAsArray="false"` then?

**Comment by jcampaner** [comment]
Other applications within the environment (which are not based on log4j2) are writing as array and they all must be consistent.

**Comment by felixbarny** [comment]
I would suggest post-processing the log file for the log viewer you are using or to use a log viewer that supports it. Which one are you using btw?

**Comment by jcampaner** [comment]
I will try to post process as suggested. Thanks.
