### ISSUE TITLE
jul-ecs-formatter not found in maven central

### ISSUE THREAD

**Issue by michaelhyatt** [elastic/ecs-logging-java#73]
Can't find the dependency to specify in my pom.xml, as per README.md:
https://github.com/elastic/ecs-logging-java/blob/master/jul-ecs-formatter/README.md

https://search.maven.org/search?q=g:co.elastic.logging%20AND%20a:jul-ecs-formatter

**Comment by felixbarny** [comment]
There hadn't been a release containing the JUL formatted up until now: https://github.com/elastic/ecs-logging-java/releases/tag/v0.4.0
