### ISSUE TITLE
Trace support for Java util logging when logging is called from SLF4j

### ISSUE THREAD

**Issue by NickWemekamp** [elastic/ecs-logging-java#78]
Hi,

I'm considering to add a feature that will add trace support for JUL when JUL is called from SLF4J. This can be done using the MDC.getCopyOfContextMap method from SLF4j. This is useful for javaee projects that want to keep using the logging framework of their application server (which is often JUL, unfortunately).

Below is a code snippet that shows how this could be implemented
```
        Map<String, String> copyOfContextMap = MDC.getCopyOfContextMap();

        copyOfContextMap.forEach((k, v) -> {
            System.out.println("key: " + k + ", value: " + v);
        });

        System.out.println(copyOfContextMap.get("trace.id"));
        System.out.println(copyOfContextMap.get("transaction.id"));
```

I can implement this by making a new formatter e.g. JuLSlf4jEcsFormatter that extends the JuLEcsFormatter, or I can edit the current JuLEcs formatter.

Which solution do you guys prefer? I prefer the last one but wanted to be sure before  I write the code :)

**Comment by felixbarny** [comment]
Good idea! I think it will be easier for users if there's only one `JulEcsFormatter` - fewer things to misconfigure. But it's a bit more tricky to implement as slf4j may or may not be available at runtime. You could do it similarly to how the optional Jackson dependency in the log4j2 layout is handled: https://github.com/elastic/ecs-logging-java/blob/master/log4j2-ecs-layout/src/main/java/co/elastic/logging/log4j2/ObjectMessageJacksonSerializer.java.

The interface may look similar to:

```java
public interface MdcSupplier {
    Map<String, String> getMDC();
}
```

And then have two different implementations depending on whether or not slf4j is on the classpath. Also make sure to mark the dependency to slf4j as `<optional>true</optional>`.
