### ISSUE TITLE
Set Content-Type Header when using EcsLayout with HTTPAppender in Log4J2

### ISSUE THREAD

**Issue by yorondevops** [elastic/ecs-logging-java#89]
Hi, 

I would like to use the "EcsLayout" together with the Log4J2 HTTP Appender to send ECS formatted logs to a service of mine, which only accepts HTTP requests of `Content-Type: application/json`. 

Previously, I used the Log4J2 provided "JsonLayout" layout in conjunction with the HTTP Appender, and according to the Log4J2 docs it was the layout that set the `Content-Type` header for requests ([source](https://logging.apache.org/log4j/2.x/manual/appenders.html#HttpAppender)).

When I use the "EcsLayout" layout, all requests are sent out with a `Content-Type: text/plain`.

I would very much appreciate it if a configuration property could be added so I could customize the `Content-Type` header while using the "EcsLayout" layout.

**Comment by felixbarny** [comment]
How does the Log4J2 HTTP Appender determine the content type?

**Comment by yorondevops** [comment]
I tried to track this behavior down myself, and while I couldn't find anything in the docs, I did locate in the source code for the JsonLayout a property of the class named "CONTENT_TYPE" (line 75) and an overriding function named "getContentType()" that returns it (line 217 )
https://logging.apache.org/log4j/2.x/log4j-core/apidocs/src-html/org/apache/logging/log4j/core/layout/JsonLayout.html

I think it's possible that adding this overriding function allows for a custom content type

**Comment by yorondevops** [comment]
Hi, I found the "root" implementation of the "getContentType()" function. It comes from the "AbstractStringLayout.java" class that your "EcsLayout" class extends. (line 232)

https://github.com/apache/logging-log4j2/blob/8229ae44ca72dbd664ee879373d2f722181ae6ce/log4j-core/src/main/java/org/apache/logging/log4j/core/layout/AbstractStringLayout.java

**Comment by felixbarny** [comment]
Ah, nice find! That would be easy to fix. But what should the content-type be? `application/json` or `application/x-ndjson`?

**Comment by yorondevops** [comment]
Seems to me like it would be best to leave the default `text/plain` it up to each user and expose the field as a configuration option, no?

Then again, I'm not sure how difficult it is to implement such functionality, I'm sure you know better than me what the best course of action is here 😄

**Comment by felixbarny** [comment]
> which only accepts HTTP requests of Content-Type: application/json

Are you sending each log line as a separate document or are you batching up multiple logs in an [NDJSON](http://ndjson.org/) format?

**Comment by yorondevops** [comment]
My aim is to send each log line as a separate JSON document.
